// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StriderWebApi.Data;

#nullable disable

namespace StriderWebApi.Migrations
{
    [DbContext(typeof(StriderDbContext))]
    [Migration("20251106023732_FixPeriodRelationships")]
    partial class FixPeriodRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoachTeam", b =>
                {
                    b.Property<int>("CoachesId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamsId")
                        .HasColumnType("integer");

                    b.HasKey("CoachesId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("CoachTeam");
                });

            modelBuilder.Entity("StriderWebApi.Domain.CoachAthleteRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AthleteId")
                        .HasColumnType("integer");

                    b.Property<int>("CoachId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("InvitationMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("InvitedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("LinkedSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("CoachId");

                    b.HasIndex("Status");

                    b.HasIndex("AthleteId", "Status");

                    b.HasIndex("CoachId", "AthleteId")
                        .IsUnique();

                    b.HasIndex("CoachId", "Status");

                    b.ToTable("CoachAthleteRelationships", (string)null);
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Ailment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AilmentType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("AthleteId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRecovered")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RecoveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("Ailments");

                    b.HasDiscriminator<string>("AilmentType").HasValue("Ailment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Interval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double?>("Distance")
                        .HasColumnType("double precision");

                    b.Property<double?>("Duration")
                        .HasColumnType("double precision");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("Percentage")
                        .HasColumnType("integer");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Intervals");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Lap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoachFeedback")
                        .HasColumnType("text");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision");

                    b.Property<double>("Duration")
                        .HasColumnType("double precision");

                    b.Property<double>("HR")
                        .HasColumnType("double precision");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<double>("Speed")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Laps");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Mesocycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Objective")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<int>("PlanningId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("WeeksCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EndDate");

                    b.HasIndex("PeriodId");

                    b.HasIndex("PlanningId");

                    b.HasIndex("StartDate");

                    b.HasIndex("Status");

                    b.ToTable("Mesocycles");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Microcycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Focus")
                        .HasColumnType("integer");

                    b.Property<string>("Intensity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MesocycleId")
                        .HasColumnType("integer");

                    b.Property<int>("Sessions")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EndDate");

                    b.HasIndex("MesocycleId");

                    b.HasIndex("StartDate");

                    b.ToTable("Microcycles");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Period", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("EndWeek")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Objective")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("PlanningId")
                        .HasColumnType("integer");

                    b.Property<int>("StartWeek")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("PlanningId");

                    b.HasIndex("Status");

                    b.ToTable("Periods");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Planning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("StartDate");

                    b.HasIndex("Status");

                    b.ToTable("Plannings");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.PlanningAthlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AthleteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("PlanningId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("PlanningId");

                    b.HasIndex("PlanningId", "AthleteId")
                        .IsUnique();

                    b.ToTable("PlanningAthletes");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CoachId")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("CoolDown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SessionType")
                        .HasColumnType("integer");

                    b.Property<int?>("TrainingPlanId")
                        .HasColumnType("integer");

                    b.Property<string>("Warmup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("TrainingPlanId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutomaticInscription")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiresManualApproval")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.TrainingGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowSelfJoin")
                        .HasColumnType("boolean");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxMembers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("RequireApproval")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Name");

                    b.ToTable("TrainingGroups");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.TrainingGroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("InvitationMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("JoinedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TrainingGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TrainingGroupId");

                    b.HasIndex("UserId");

                    b.HasIndex("TrainingGroupId", "UserId")
                        .IsUnique();

                    b.ToTable("TrainingGroupMembers");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.TrainingInterval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Distance")
                        .HasColumnType("numeric");

                    b.Property<string>("Duration")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Intensity")
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Pace")
                        .HasColumnType("numeric");

                    b.Property<string>("PaceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecoveryTime")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("00:00");

                    b.Property<int>("Repetitions")
                        .HasColumnType("integer");

                    b.Property<string>("TargetSpeed")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TargetTime")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TrainingMode")
                        .HasColumnType("text");

                    b.Property<int?>("TrainingSessionId")
                        .HasColumnType("integer");

                    b.Property<int?>("TrainingTemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Vo2MaxPercentage")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("TrainingSessionId");

                    b.HasIndex("TrainingTemplateId");

                    b.HasIndex("TrainingSessionId", "OrderIndex");

                    b.HasIndex("TrainingTemplateId", "OrderIndex");

                    b.ToTable("TrainingIntervals", null, t =>
                        {
                            t.HasCheckConstraint("CK_TrainingInterval_SingleParent", "((\"TrainingTemplateId\" IS NULL AND \"TrainingSessionId\" IS NOT NULL) OR (\"TrainingTemplateId\" IS NOT NULL AND \"TrainingSessionId\" IS NULL))");
                        });
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.TrainingLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("TrainingLocations");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.TrainingPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.ToTable("TrainingPlans");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.TrainingPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TrainingGroupId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrainingGroupId");

                    b.ToTable("TrainingPoints");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.TrainingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("MicrocycleId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("PlanningId")
                        .HasColumnType("integer");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Date");

                    b.HasIndex("MicrocycleId");

                    b.HasIndex("PlanningId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("CreatedByUserId", "Date");

                    b.ToTable("TrainingSessions", (string)null);
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.TrainingSessionAthlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualAvgHR")
                        .HasColumnType("integer");

                    b.Property<string>("ActualAvgPace")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<double?>("ActualDistance")
                        .HasColumnType("double precision");

                    b.Property<int?>("ActualDuration")
                        .HasColumnType("integer");

                    b.Property<int?>("ActualMaxHR")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("AthleteId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TrainingSessionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("Status");

                    b.HasIndex("AthleteId", "Status");

                    b.HasIndex("TrainingSessionId", "AthleteId")
                        .IsUnique();

                    b.HasIndex("TrainingSessionId", "Status");

                    b.ToTable("TrainingSessionAthletes", (string)null);
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.TrainingTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CoolDownDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("CoolDownDuration")
                        .HasColumnType("integer");

                    b.Property<string>("CoolDownPace")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Distance")
                        .HasColumnType("numeric");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastUsed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TargetHR")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TargetPace")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UseCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("WarmUpDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("WarmUpDuration")
                        .HasColumnType("integer");

                    b.Property<string>("WarmUpPace")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsFavorite");

                    b.HasIndex("Name");

                    b.HasIndex("Tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

                    b.HasIndex("Type", "Category");

                    b.ToTable("TrainingTemplates", (string)null);
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivationToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ActivationTokenExpires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PreferredTheme")
                        .HasColumnType("integer");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserType")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email", "UserType")
                        .IsUnique();

                    b.HasIndex("Username", "UserType")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasDiscriminator<int>("UserType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AthleteId")
                        .HasColumnType("integer");

                    b.Property<double>("AverageHR")
                        .HasColumnType("double precision");

                    b.Property<string>("CoachFeedback")
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision");

                    b.Property<double>("Duration")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SessionId")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("SessionId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Illness", b =>
                {
                    b.HasBaseType("StriderWebApi.Domain.DomainClasses.Ailment");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Illness");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Injury", b =>
                {
                    b.HasBaseType("StriderWebApi.Domain.DomainClasses.Ailment");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Ailments", t =>
                        {
                            t.Property("Type")
                                .HasColumnName("Injury_Type");
                        });

                    b.HasDiscriminator().HasValue("Injury");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Athlete", b =>
                {
                    b.HasBaseType("StriderWebApi.Domain.DomainClasses.User");

                    b.Property<int?>("CoachId")
                        .HasColumnType("integer");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactRelationship")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<List<string>>("MedicalConditions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<string>>("Objectives")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingVolumeKm")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingVolumeType")
                        .HasColumnType("integer");

                    b.Property<double?>("VO2Max")
                        .HasColumnType("double precision");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasIndex("CoachId");

                    b.HasIndex("TeamId");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Coach", b =>
                {
                    b.HasBaseType("StriderWebApi.Domain.DomainClasses.User");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("CoachTeam", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.Coach", null)
                        .WithMany()
                        .HasForeignKey("CoachesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StriderWebApi.Domain.DomainClasses.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StriderWebApi.Domain.CoachAthleteRelationship", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.User", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StriderWebApi.Domain.DomainClasses.User", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Ailment", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.Athlete", "Athlete")
                        .WithMany("Ailments")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Interval", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.Session", "Session")
                        .WithMany("Intervals")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Lap", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.Workout", "Workout")
                        .WithMany("Laps")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Mesocycle", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.Period", "Period")
                        .WithMany("Mesocycles")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StriderWebApi.Domain.DomainClasses.Planning", "Planning")
                        .WithMany("Mesocycles")
                        .HasForeignKey("PlanningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");

                    b.Navigation("Planning");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Microcycle", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.Mesocycle", "Mesocycle")
                        .WithMany("Microcycles")
                        .HasForeignKey("MesocycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mesocycle");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Notification", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Period", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.Planning", "Planning")
                        .WithMany("Periods")
                        .HasForeignKey("PlanningId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Planning");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Planning", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.User", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.PlanningAthlete", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.User", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StriderWebApi.Domain.DomainClasses.Planning", "Planning")
                        .WithMany("PlanningAthletes")
                        .HasForeignKey("PlanningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("Planning");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Session", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.Coach", null)
                        .WithMany("Templates")
                        .HasForeignKey("CoachId");

                    b.HasOne("StriderWebApi.Domain.DomainClasses.TrainingPlan", "TrainingPlan")
                        .WithMany("Sessions")
                        .HasForeignKey("TrainingPlanId");

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.TrainingGroup", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("StriderWebApi.Domain.DomainClasses.TrainingGroupNotifications", "Notifications", b1 =>
                        {
                            b1.Property<int>("TrainingGroupId")
                                .HasColumnType("integer");

                            b1.Property<bool>("CompletedWorkouts")
                                .HasColumnType("boolean");

                            b1.Property<bool>("Injuries")
                                .HasColumnType("boolean");

                            b1.Property<bool>("MissedSessions")
                                .HasColumnType("boolean");

                            b1.Property<bool>("NewMembers")
                                .HasColumnType("boolean");

                            b1.HasKey("TrainingGroupId");

                            b1.ToTable("TrainingGroups");

                            b1.WithOwner()
                                .HasForeignKey("TrainingGroupId");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.TrainingGroupMember", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.TrainingGroup", "TrainingGroup")
                        .WithMany("Members")
                        .HasForeignKey("TrainingGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StriderWebApi.Domain.DomainClasses.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TrainingGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.TrainingInterval", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.TrainingSession", "TrainingSession")
                        .WithMany("Intervals")
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StriderWebApi.Domain.DomainClasses.TrainingTemplate", "TrainingTemplate")
                        .WithMany("Intervals")
                        .HasForeignKey("TrainingTemplateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TrainingSession");

                    b.Navigation("TrainingTemplate");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.TrainingLocation", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.Team", null)
                        .WithMany("TrainingLocations")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.TrainingPlan", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.Coach", "Coach")
                        .WithMany("TrainingPlans")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.TrainingPoint", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.TrainingGroup", "TrainingGroup")
                        .WithMany("TrainingPoints")
                        .HasForeignKey("TrainingGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingGroup");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.TrainingSession", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StriderWebApi.Domain.DomainClasses.Microcycle", "Microcycle")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("MicrocycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StriderWebApi.Domain.DomainClasses.Planning", "Planning")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("PlanningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StriderWebApi.Domain.DomainClasses.TrainingTemplate", "Template")
                        .WithMany("Sessions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");

                    b.Navigation("Microcycle");

                    b.Navigation("Planning");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.TrainingSessionAthlete", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.User", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StriderWebApi.Domain.DomainClasses.TrainingSession", "TrainingSession")
                        .WithMany("Athletes")
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Workout", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.Athlete", "Athlete")
                        .WithMany("Workouts")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StriderWebApi.Domain.DomainClasses.Session", "Session")
                        .WithMany("Workouts")
                        .HasForeignKey("SessionId");

                    b.Navigation("Athlete");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Athlete", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.Coach", null)
                        .WithMany("Athletes")
                        .HasForeignKey("CoachId");

                    b.HasOne("StriderWebApi.Domain.DomainClasses.Team", "Team")
                        .WithMany("Athletes")
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Mesocycle", b =>
                {
                    b.Navigation("Microcycles");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Microcycle", b =>
                {
                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Period", b =>
                {
                    b.Navigation("Mesocycles");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Planning", b =>
                {
                    b.Navigation("Mesocycles");

                    b.Navigation("Periods");

                    b.Navigation("PlanningAthletes");

                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Session", b =>
                {
                    b.Navigation("Intervals");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Team", b =>
                {
                    b.Navigation("Athletes");

                    b.Navigation("TrainingLocations");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.TrainingGroup", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("TrainingPoints");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.TrainingPlan", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.TrainingSession", b =>
                {
                    b.Navigation("Athletes");

                    b.Navigation("Intervals");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.TrainingTemplate", b =>
                {
                    b.Navigation("Intervals");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Workout", b =>
                {
                    b.Navigation("Laps");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Athlete", b =>
                {
                    b.Navigation("Ailments");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Coach", b =>
                {
                    b.Navigation("Athletes");

                    b.Navigation("Templates");

                    b.Navigation("TrainingPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
