// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StriderWebApi.Data;

#nullable disable

namespace StriderWebApi.Migrations
{
    [DbContext(typeof(StriderDbContext))]
    partial class StriderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoachTeam", b =>
                {
                    b.Property<int>("CoachesId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamsId")
                        .HasColumnType("integer");

                    b.HasKey("CoachesId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("CoachTeam");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Ailment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AilmentType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("AthleteId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRecovered")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RecoveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("Ailments");

                    b.HasDiscriminator<string>("AilmentType").HasValue("Ailment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Interval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double?>("Distance")
                        .HasColumnType("double precision");

                    b.Property<double?>("Duration")
                        .HasColumnType("double precision");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("Percentage")
                        .HasColumnType("integer");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Intervals");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Lap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoachFeedback")
                        .HasColumnType("text");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision");

                    b.Property<double>("Duration")
                        .HasColumnType("double precision");

                    b.Property<double>("HR")
                        .HasColumnType("double precision");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<double>("Speed")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Laps");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CoachId")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("CoolDown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SessionType")
                        .HasColumnType("integer");

                    b.Property<int?>("TrainingPlanId")
                        .HasColumnType("integer");

                    b.Property<string>("Warmup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("TrainingPlanId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutomaticInscription")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiresManualApproval")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.TrainingLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("TrainingLocations");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.TrainingPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.ToTable("TrainingPlans");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivationToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ActivationTokenExpires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserType")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasDiscriminator<int>("UserType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AthleteId")
                        .HasColumnType("integer");

                    b.Property<double>("AverageHR")
                        .HasColumnType("double precision");

                    b.Property<string>("CoachFeedback")
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision");

                    b.Property<double>("Duration")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SessionId")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("SessionId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Illness", b =>
                {
                    b.HasBaseType("StriderWebApi.Domain.DomainClasses.Ailment");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Illness");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Injury", b =>
                {
                    b.HasBaseType("StriderWebApi.Domain.DomainClasses.Ailment");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Ailments", t =>
                        {
                            t.Property("Type")
                                .HasColumnName("Injury_Type");
                        });

                    b.HasDiscriminator().HasValue("Injury");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Athlete", b =>
                {
                    b.HasBaseType("StriderWebApi.Domain.DomainClasses.User");

                    b.Property<int?>("CoachId")
                        .HasColumnType("integer");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactRelationship")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<List<string>>("MedicalConditions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<string>>("Objectives")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingVolumeKm")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingVolumeType")
                        .HasColumnType("integer");

                    b.Property<double?>("VO2Max")
                        .HasColumnType("double precision");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasIndex("CoachId");

                    b.HasIndex("TeamId");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Coach", b =>
                {
                    b.HasBaseType("StriderWebApi.Domain.DomainClasses.User");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("CoachTeam", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.Coach", null)
                        .WithMany()
                        .HasForeignKey("CoachesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StriderWebApi.Domain.DomainClasses.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Ailment", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.Athlete", "Athlete")
                        .WithMany("Ailments")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Interval", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.Session", "Session")
                        .WithMany("Intervals")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Lap", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.Workout", "Workout")
                        .WithMany("Laps")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Notification", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Session", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.Coach", null)
                        .WithMany("Templates")
                        .HasForeignKey("CoachId");

                    b.HasOne("StriderWebApi.Domain.DomainClasses.TrainingPlan", "TrainingPlan")
                        .WithMany("Sessions")
                        .HasForeignKey("TrainingPlanId");

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.TrainingLocation", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.Team", null)
                        .WithMany("TrainingLocations")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.TrainingPlan", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.Coach", "Coach")
                        .WithMany("TrainingPlans")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Workout", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.Athlete", "Athlete")
                        .WithMany("Workouts")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StriderWebApi.Domain.DomainClasses.Session", "Session")
                        .WithMany("Workouts")
                        .HasForeignKey("SessionId");

                    b.Navigation("Athlete");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Athlete", b =>
                {
                    b.HasOne("StriderWebApi.Domain.DomainClasses.Coach", null)
                        .WithMany("Athletes")
                        .HasForeignKey("CoachId");

                    b.HasOne("StriderWebApi.Domain.DomainClasses.Team", "Team")
                        .WithMany("Athletes")
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Session", b =>
                {
                    b.Navigation("Intervals");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Team", b =>
                {
                    b.Navigation("Athletes");

                    b.Navigation("TrainingLocations");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.TrainingPlan", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Workout", b =>
                {
                    b.Navigation("Laps");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Athlete", b =>
                {
                    b.Navigation("Ailments");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("StriderWebApi.Domain.DomainClasses.Coach", b =>
                {
                    b.Navigation("Athletes");

                    b.Navigation("Templates");

                    b.Navigation("TrainingPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
