namespace StriderWebApi.Domain.Enums
{
    public enum InjuryLocation
    {
        Head,
        Neck,
        RightShoulder,
        LeftShoulder,
        RightArm,
        LeftArm,
        RightElbow,
        LeftElbow,
        RightWrist,
        LeftWrist,
        RightHand,
        LeftHand,
        Chest,
        UpperBack,
        LowerBack,
        Abdomen,
        Hip,
        RightThigh,
        LeftThigh,
        RightKnee,
        LeftKnee,
        RightCalf,
        LeftCalf,
        RightAnkle,
        LeftAnkle,
        RightFoot,
        LeftFoot,
        RightAchilles,
        LeftAchilles
    }
} 